### ISSUE TITLE
Mesh6LoWPAN_ND v.s MeshThread

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/mbed-mesh-api#12]
In Wiki article: Thread uses 6LoWPAN, which in turn uses the IEEE 802.15.4 wireless protocol with mesh communication.
It seems reveal Thread-mesh equal to 6LowPan-mesh.
What's the difference between Mesh6LoWPAN_ND and MeshThread ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2283

**Comment by artokin** [comment]
Currently NanoStack (https://github.com/ARMmbed/sal-stack-nanostack) supports two bootstrap modes that are: 
* 6LoWPAN (https://docs.mbed.com/docs/arm-ipv66lowpan-stack/en/stable/02_N_arch/index.html)
* Thread (https://docs.mbed.com/docs/arm-ipv66lowpan-stack/en/stable/thread_overview/index.html)

Both bootstrap  modes are using 6LoWPAN protocol but are using different protocols on top of 6LoWPAN. For example, in 6LoWPAN mode the NanoStack is using ND(neighbor discovery) and MLE (Mesh Link Establishment) while in Thread mode TMF (Thread Management Framework) protocol is used.

`MeshThread` will be an interface to a NanoStack that is configured to Thread mode. `Mesh6LoWPAN_ND` will be an interface to a NanoStack that is configured to 6LoWPAN bootstrap mode. We are expecting that the interfaces will be slightly different in the future and therefore both bootstrap modes are having own classes. Functionality that is shared between 6LoWPAN and Thread modes will be available in `AbstractMesh`.

**Comment by cyliangtw** [comment]
Thanks. According to my measurement of mbed-client-example-6lowpan-master, to change Mesh6LoWPAN_ND as MeshThread mode could save 95KB ROM size, what's the disadvantage of  MeshThread mode v.s Mesh6LoWPAN_ND ?

**Comment by artokin** [comment]
6LoWPAN bootstrap mode is using standardized protocols while current implementation of Thread is experimental. Please see documentation of different bootstrap modes from NanoStack documentation (links in my previous post).

At the moment NanoStack is having both bootstrap modes active by default and mbedOS application can select which mode to use. There shouldn't be any big difference in the ROM size. ARM mbed partners can utilize NanoStack build time configuration using instructions in https://docs.mbed.com/docs/arm-ipv66lowpan-stack/en/latest/configuring/index.html. The page also contains rough estimate about the ROM size using different configurations.

**Comment by cyliangtw** [comment]
Thanks, the reference ROM size is valuable. It's better with RAM size.
