### ISSUE TITLE
Macro definition of 6LoWPAN ND security mode 

### ISSUE THREAD

**Issue by borting** [ARMmbed/mbed-mesh-api#33]
Hi,

I think there might be a typo in **source/include/static_config.h** when defining the default value of 6LoWPAN ND security mode.

In the else description, **YOTTA_CFG_MBED_MESH_API_6LOWPAN_ND_SECURITY_MODE** is better to be replaced with **MBED_MESH_API_6LOWPAN_ND_SECURITY_MODE**. Otherwise the nd_tasklet.c would get a string of macro name from parsing instead of "NONE".

And [here](https://github.com/borting/mbed-mesh-api/commit/a4e10aebe0368008228e8104d0d51d4448841b5e) is my patch to this. Thank you.

Best regards,
Borting

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2736

**Comment by hasnainvirk** [comment]
This issue was resolved in https://github.com/ARMmbed/mbed-mesh-api/commit/597d6d354301585d0c3677126699bd72ebca30c9
